apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiZ2l0aHViYWN0aW9ucmVnaXN0b3J5LmF6dXJlY3IuaW8iOiB7ImF1dGgiOiAiWjJsMGFIVmlZV04wYVc5dWNtVm5hWE4wYjNKNU9tMURURlo2VDJZMVkzRlhWVEkxWWxod1ZERmhWbTVqWWpKVVZIZFRWak5ZTlM5dE56VTJWV1J5ZUN0QlExSkJkVWc0V25JPSJ9fX0=
type: kubernetes.io/dockerconfigjson
