apiVersion: v1
kind: Service
metadata:
  name: my-serv
spec:
  selector:
    app: app
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8000      
    targetPort: 80      
    nodePort: 31000
