apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: hamritha817/github-action-maven-tutorial:287fbbd3d316e8663ac41324481ec8a92b8d1240
          ports:
            - containerPort: 80  # Adjust the container port as needed
