apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: hamritha817/github-action-maven-tutorial:b01c67689b561a1a1b45a0ccf502e69e63be98b8
          ports:
            - containerPort: 80  # Adjust the container port as needed
