apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image:  hamritha817/github-action-maven-tutorial:11f86a7ac1996aede7a314b99bd4207012dbff2d
            - containerPort: 80  # Adjust the container port as needed
