apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: hamritha817/github-action-maven-tutorial:2b8b9e5afac9729f4e6d9948d8b01f33db13e37b
          ports:
            - containerPort: 80  # Adjust the container port as needed
