apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: hamritha817/github-action-maven-tutorial:22f696b2adf4ee606dc8aeeccdaee79723c2d770
          ports:
            - containerPort: 80  # Adjust the container port as needed
